ACCESS_TOKEN_LIFE: 86400000
API_KEY: DocsSharing.dmFudGh1YW5ob2FuZ2FuaDIwMjM=
REFRESH_TOKEN_LIFE: 86400000
EMAIL_SENDER: thuanmyhoa7a2@gmail.com

server:
  servlet:
    context-path: /docs-sharing
  forward-headers-strategy: framework
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 01669871043
    url: jdbc:mysql://localhost:3306/docs_sharing
    username: root
  devtools:
    restart:
      log-condition-evaluation-delta: false
  jackson:
    time-zone: Asia/Bangkok
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
      show_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    password: dmcymrlbgvcimryp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: thuanmyhoa7a2@gmail.com

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    operationsSorter: method
    path: /api/v1/swagger-ui
    try-it-out-enabled: true